### ISSUE TITLE
Un bon fichier README

### ISSUE THREAD

**Issue by dofbi** [Code-for-Senegal/Senegal-Report-Incidents-FRONT-END#1]
Hello @diadjii
Je découvre ce repo **[Senegal-Report-Incidents](https://github.com/Code-for-Senegal/Senegal-Report-Incidents)** peut tu m'aider à mieux comprendre ce projet.

- Que fait ce projet?
- Pourquoi ce projet est-il utile?
- Comment puis-je contribuer?
- Où puis-je obtenir plus d’aide, si j’en ai besoin?

Tu peut utiliser le fichier [README](https://github.com/Code-for-Senegal/Senegal-Report-Incidents/blob/main/README.md) pour réponde.

La rédaction d'un bon fichier README est trés important pour **Code for Senegal**

Voici un **[template README](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)**

Merci

**Comment by diadjii** [comment]
Salam @dofbi 
ok je vais faire ça

**Comment by dofbi** [comment]
Cool, J'attends de lire ton commit #1

**Comment by dofbi** [comment]
Hello @diadjii 
J'ai vu l'évolution du README c'est bien

- Tu peux t'inspirer d'[Etat](https://github.com/Code-for-Senegal/etat) pour la partie **Contribution**
- Il est important d'ajouter les informations concernant l'environnement de développement du projet, pour ton cas, c'est du REACT, comment clone, install et lancer le serveur
- License
- À propos de Code for Senegal

N'oublie pas d'ajouter dans le message de ton commit #1 cela le relis aux issues de manière automatique

Merci

**Comment by diadjii** [comment]
salam @dofbi  
d'accord je vais faire ça et merci pour les suggestions

**Comment by diadjii** [comment]
@dofbi comment tu vas ?, j'ai mis à jour le fichier README tu peux le consulter et s'il y'a des modifications tu me dis

**Comment by dofbi** [comment]
Salaam @diadjii 
Je vais bien merci à toi, oui, c'est beaucoup mieux.
N'hésite pas update en avançant dans le projet.
Et à ouvrir des issues pour motiver la Team à contribuer
Good job, tu viens de décrocher ton titre de [chevalier](https://github.com/Code-for-Senegal/Diambars-Decorations) 🎖️🇸🇳 👍🏾
